package actions

import (
	"testing"

	"github.com/gobuffalo/suite"
)

type ActionSuite struct {
	*suite.Action
}

func Test_ActionSuite(t *testing.T) {
	as := &ActionSuite{suite.NewAction(App())}
	suite.Run(t, as)
}

func (as ActionSuite) setAuthorization() {
	as.Willie.Headers["Authorization"] = "bearer " + "eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmOTM0NzJmN2M5ZDhlZTJkMmRlZDM5M2QxMGJjY2E5ZTNiYmUzNjkifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZ290di1kZXYiLCJhdWQiOiJnb3R2LWRldiIsImF1dGhfdGltZSI6MTUxODQzNTUzOCwidXNlcl9pZCI6IkpOTklYN1BTemlSbndUQVRsMHRUUWg1cnM5RzIiLCJzdWIiOiJKTk5JWDdQU3ppUm53VEFUbDB0VFFoNXJzOUcyIiwiaWF0IjoxNTE4NDM1NTM4LCJleHAiOjE1MTg0MzkxMzgsImVtYWlsIjoidGVzdDFAdGVzdC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdDFAdGVzdC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.efm0kIjSbcx339PSHdx5QaiO6tfODTtSqvL2rHE05ln4s6aEQ0HJMeOEkqoN49jSbBpLQIvirp5wFt0S4ztb2vADSxs0daulRLggFCavXunF_bG7AMlp0NwEaC4fStIGmcTQlhVDeMdLBDf2xeW36bPuD6k27V3MWNQRFxRIcd4ETTSaGKqVjxo_oZ7-dwfBgawCgrzzHwxZp2W0JRSwj15tjfKI_oS_lPtP4q2fBZC-0lJhKsKpbwtyehiWHZFucKLCTAgp2pVfhBkDkIyfdQXnkzKRT0L0iPZn14PD4LDUIIT1zdpJikPdkJ_sS0ZbHw0O5koAJsOpwS11wPNrFQ"
}
