package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
	"github.com/wung-s/gotv/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Role)
// DB Table: Plural (roles)
// Resource: Plural (Roles)
// Path: Plural (/roles)
// View Template Folder: Plural (/templates/roles/)

// RolesResource is the resource for the Role model
type RolesResource struct {
	buffalo.Resource
}

// List gets all Roles. This function is mapped to the path
// GET /roles
func (v RolesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	roles := &models.Roles{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Roles from the DB
	if err := q.All(roles); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the headers so clients know how to paginate.
	c.Response().Header().Set("X-Pagination", q.Paginator.String())

	return c.Render(200, r.JSON(roles))
}

// Show gets the data for one Role. This function is mapped to
// the path GET /roles/{role_id}
func (v RolesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Role
	role := &models.Role{}

	// To find the Role the parameter role_id is used.
	if err := tx.Find(role, c.Param("role_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.JSON(role))
}

// New default implementation. Returns a 404
func (v RolesResource) New(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Create adds a Role to the DB. This function is mapped to the
// path POST /roles
func (v RolesResource) Create(c buffalo.Context) error {
	// Allocate an empty Role
	role := &models.Role{}

	// Bind role to the html form elements
	if err := c.Bind(role); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(role)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(201, r.JSON(role))
}

// Edit default implementation. Returns a 404
func (v RolesResource) Edit(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Update changes a Role in the DB. This function is mapped to
// the path PUT /roles/{role_id}
func (v RolesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Role
	role := &models.Role{}

	if err := tx.Find(role, c.Param("role_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Role to the html form elements
	if err := c.Bind(role); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(role)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(200, r.JSON(role))
}

// Destroy deletes a Role from the DB. This function is mapped
// to the path DELETE /roles/{role_id}
func (v RolesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Role
	role := &models.Role{}

	// To find the Role the parameter role_id is used.
	if err := tx.Find(role, c.Param("role_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(role); err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.JSON(role))
}
